### ISSUE TITLE
Add repos or configuration

### ISSUE THREAD

**Issue by rothgar** [vladkens/ghstats#1]
I haven't found any docs or examples on how to add repos to watch. I'm still looking for it but opening an issue to add docs/examples later.

**Comment by vladkens** [comment]
@rothgar Hi. Current version of this program monitors all **owned** repos, so there is no special configuration.

If you need something special - I can add it.

**Comment by rothgar** [comment]
Mine isn't loading any repos so maybe my token isn't working 

![image](https://github.com/user-attachments/assets/2b1813b5-7287-46d9-b29d-4e30fd38b818)

I'm part of a few different organizations and have various degrees of permissions to the repos. It would be nice if I could explicitly list the repos I want to track.

**Comment by rothgar** [comment]
Realized the api updates are failing so my token must not have the proper permissions. I'll try again.

**Comment by ruanbekker** [comment]
Hey @rothgar , I am getting the same response. Did you manage to resolve it?

**Comment by rothgar** [comment]
I tried again with a couple different API keys (new and classic) and never got it to load repos.
I was going to try again with a key that has more permissions but haven't yet.

**Comment by ruanbekker** [comment]
Interesting, it seems like that app isn't using the token. I've been running it for about 4 hours, and the app logs:

```bash
ghstats-github-stats-6ffd96c86b-qb9v4 github-stats 2024-08-10T18:20:59.584630Z  INFO request: finished processing request latency=0 ms status=200 method=GET uri=/ version=HTTP/1.1
```

I double checked the environment inside the pod:

```bash
env | grep TOKEN
GITHUB_TOKEN=ghp_mv..........
```

And I noticed that github says the token was not used:

<img width="884" alt="image" src="https://github.com/user-attachments/assets/51405718-8acb-4c21-9452-3f427065089a">

**Comment by vladkens** [comment]
Hi, @rothgar @ruanbekker

How do you run the app? I have tried different ways, even recreated the token according to instructions in the readme file and it succeeds every time for me.

For examplw launch command:
```sh
docker run -e GITHUB_TOKEN=ghp_123 -p 8080:8080 -v ./data:/app/data --name ghstats ghcr.io/vladkens/ghstats:latest
```

Initial logs:
```
2024-08-11-11T20:11:25.729315Z INFO db_path: ./data/ghstats.db
2024-08-11-11T20:11:25.742995Z INFO update_deltas took 791.261µs
2024-08-11-11T20:12:03.312666Z INFO update_metrics took 37.569416944s
2024-08-11T20:12:03.316439Z INFO update_deltas took 3.759095ms
2024-08-11-11T20:12:03.316605Z INFO Job creator created
2024-08-11T20:12:03.316652Z INFO listening on 0.0.0.0.0:8080
```

On a fresh database (when no repo is found) app always tries to load initial stats.

**Comment by emouawad** [comment]
Same here not working on k8s v0.5.0

**Comment by rothgar** [comment]
I just tested again (v0.5.0) with a classic GH token with access to public repos and it worked for me. It doesn't show any of the orgs that I'm a part of (I didn't expect it to) so I'm going to see if I can make a token for those orgs.

**Comment by emouawad** [comment]
Oh now i noticed, only public repos are targeted - my assumption was "private" org repos as well.
Kind of curious why only public ones? there is value - if possible - in this being for private org repos too.

**Comment by t0mmili** [comment]
> Oh now i noticed, only public repos are targeted - my assumption was "private" org repos as well. Kind of curious why only public ones? there is value - if possible - in this being for private org repos too.

That's the question for @vladkens. Public visibility filter is hardcoded. Also, public repo scope for token is suggested.

**Comment by vladkens** [comment]
Private repos support added in https://github.com/vladkens/ghstats/issues/17
