### ISSUE TITLE
Removed repos still listed

### ISSUE THREAD

**Issue by R0GGER** [vladkens/ghstats#10]
Version: ghstats v0.2.0

A few days ago I removed a few unused repos, but they are still listed in ghstats.
When I restart ghstat the repos are still listed.
Bug?

**Comment by vladkens** [comment]
Hi, @R0GGER.

Fixed in [v0.3.0](https://github.com/vladkens/ghstats/releases/tag/v0.3.0)

**Comment by R0GGER** [comment]
Great! Thanks! :+1:
