### ISSUE TITLE
ghstats behind reverse proxy (nginx)

### ISSUE THREAD

**Issue by t0mmili** [vladkens/ghstats#11]
Hi,

I'm trying to run ghstats behing nginx, so it's accessible on the nice local domain `https://ghstats.something.local`.

But it's failing...

```
2024/08/26 13:00:57 [error] 16#16: *35 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.x.x, server: ghstats.something.local, request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.29.x.x:8383/favicon.ico", host: "ghstats.something.local", referrer: "https://ghstats.something.local/"
```

I'm running ghstats with docker compose, port redirection: `8383:8080`.

Are you able to confirm or deny that it's possible currently?

I can provide additional details if needed.

**Comment by t0mmili** [comment]
Nvm, I found `PORT` and `HOST` env variables in the code. Problem solved 😄 
Should be documented probably.

**Comment by vladkens** [comment]
@t0mmili hi, thank you for feedback. I was adding those variables just to have them. But now I know they may be needed. I'll add it to readme.
