### ISSUE TITLE
Feature API?

### ISSUE THREAD

**Issue by sahara101** [vladkens/ghstats#12]
Hi!

Any chance to get API support? So I can add ghstats to Homepage. 

Thanks!

**Comment by vladkens** [comment]
Hi, @sahara101.

What kind of data you want to get thought this API?

**Comment by sahara101** [comment]
Hi! Total number of repos, clones, issues, stars and views. All time if possible. 

Thanks!

**Comment by vladkens** [comment]
Hi, @sahara101. I've been busy past weeks.

Feature was added to `main` few weeks ago and released in `v0.4.0`. Check docs here: https://github.com/vladkens/ghstats?tab=readme-ov-file#api-endpoint

**Comment by sahara101** [comment]
Thanks!
