### ISSUE TITLE
Feature Request - private org repos

### ISSUE THREAD

**Issue by emouawad** [vladkens/ghstats#17]
ghstats for private org repos as well. 

Private org repos have the traffic metrics as well.

use repos `all` instead of `public` in the gh api call or make it configurable.

**Comment by vladkens** [comment]
Hi, @emouawad. Released in [v0.6.0](https://github.com/vladkens/ghstats/releases/tag/v0.6.0)

To access private repos you need:
- generate token which have access to private repos, see [here](https://github.com/vladkens/ghstats?tab=readme-ov-file#github-token-generation)
- set `GHS_INCLUDE_PRIVATE=true` environment variable

**Comment by emouawad** [comment]
Wonderful - Tested it: it's working on kubernetes as expected! Thanks ❤️
