### ISSUE TITLE
[Bug] Filters order is important?

### ISSUE THREAD

**Issue by t0mmili** [vladkens/ghstats#18]
Hi @vladkens,

Just tested v0.6.0, filtering to be specific. Either I found a bug or didn't understood docs or docs require clarification.

**Test case 1**
`GHS_FILTER=t0mmili/*,!t0mmili/taiko-ci`
OK. Shows all my public repos except `taiko-ci`.

**Test case 2**
`GHS_FILTER=!t0mmili/taiko-ci,t0mmili/*`
WRONG. Shows all my public repos, including other orgs I'm part of.

**Test case 3**
`GHS_FILTER=t0mmili/*,!fork`
OK. Shows all my public repos except forks.

**Test case 4**
`GHS_FILTER=!fork,t0mmili/*`
WRONG. Shows all my public repos, including other orgs I'm part of.

So, generally, it looks like negations should be placed in the end. Please clarify, what's the situation here.

**Comment by vladkens** [comment]
Hi, @t0mmili. Order shouldn't have relevance. I added test [here](https://github.com/vladkens/ghstats/commit/561a747566cd4f76dc5b17bf9ed0ade8b4c58037) and it [passed](https://github.com/vladkens/ghstats/actions/runs/11449407797/job/31854923366)

**Comment by t0mmili** [comment]
I did further digging.
First, I compiled app locally and tried above test cases. Order is not relevant 😮 
Next I went back to original test, which was done with docker image running behind reverse proxy. It still fails when negation is first...

I will try to inspect this further and leave some updates here.

**Comment by t0mmili** [comment]
@vladkens problem solved!

Previously my GHS_FILTER value didn't have quotations. This is correct and works ok:
```
    environment:
      GHS_FILTER: "!fork,t0mmili/*"
```

**Comment by vladkens** [comment]
Hi, @t0mmili. Here an article about: https://binfalse.de/2024/05/31/docker-compose-quotation-pitfalls/

If you use KV environments format in compose.yaml, complex strings should be escaped with `"`. This is related to YAML parser

**Comment by t0mmili** [comment]
Thanks @vladkens, I did know that, just had a memory fog somehow 😄 Closing this one.
