### ISSUE TITLE
Sorting by views reset the time period set

### ISSUE THREAD

**Issue by Lexedia** [vladkens/ghstats#19]
See the attached gif

![2024-10-24 21-06-45-2](https://github.com/user-attachments/assets/a5a282fa-beff-435a-b177-8fa0cdc9b48a)

**Comment by vladkens** [comment]
Hi, @Rapougnac. Thank you for reporting it. Fixed in [v0.6.1](https://github.com/vladkens/ghstats/releases/tag/v0.6.1)

**Comment by Lexedia** [comment]
Thank you so much! It works perfectly now
