### ISSUE TITLE
Organization support?

### ISSUE THREAD

**Issue by Noxits** [vladkens/ghstats#2]
Hi,
I see you're filtering the repos only owned by the current user, any reasons behind this reasoning?

**Comment by DTheIcyDragon** [comment]
Hey, I'd like to see Oraganization support too, since I am coding mostly on a org and only like testing stuff on my private profile

Still a project I am going to self host :P

**Comment by vladkens** [comment]
Hi. In general, technically there are no restrictions on getting organizations. I need to somehow understand if the current user has access to traffic api or not. I'll add this soon.

**Comment by vladkens** [comment]
@Noxits @DTheIcyDragon

Hi, again. Just released [new version](https://github.com/vladkens/ghstats/releases/tag/v0.2.0) – it should now load organisations repos too (if repo is public).

Check please

**Comment by Noxits** [comment]
Sweet, thanks, works like a charm now!
