### ISSUE TITLE
[Feature Request] - Docker Healthcheck

### ISSUE THREAD

**Issue by modem7** [vladkens/ghstats#7]
To make sure the container is running properly/has failure handling via the Docker healthcheck, I propose a app specific docker healthcheck so we can do the aforementioned. 

e.g. https://github.com/samuelba/healthcheck or https://github.com/cloudlena/healthcheck

Maybe check that the page loads with the right content (e.g. a curl check may show that the webserver is up and responding, but that doesn't necessarily mean the page has the expected content), and maybe checks that the latest cron job has pulled the stats correctly (e.g. in case of a network issue due to user or wider error or token error)

**Comment by vladkens** [comment]
Hi, @modem7. Released in [v0.3.0](https://github.com/vladkens/ghstats/releases/tag/v0.3.0)
